apiVersion: v1
kind: Service
metadata:
  name: seniority-calculator-service 
  labels:
    app: seniority-calculator-service
    example: monitoring-custom-metrics
spec:
  ports:
  - name: http
    port: 4004
    targetPort: 4004
  selector:
    app: seniority-calculator-service 